name: espota
description: ArduinoOTA protocol for ESPRESSIF chips.
repository: https://github.com/X-dea/espota.dart
version: 1.0.0+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  args: ^2.0.0
  convert: ^3.0.0
  crypto: ^3.0.0

dev_dependencies:
  lints: ^2.0.0
